name: Train and Evaluate ML Model

on:
  push:
    branches: [ main ]   # Runs when code is pushed to main
  pull_request:          # Also runs when PRs are opened
    branches: [ main ]

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Train model
      - name: Train Model
        run: |
          python train.py

      # Step 5: Evaluate model
      - name: Evaluate Model
        run: |
          python evaluate.py

      # Step 6: Upload artifacts (e.g., trained model file)
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl
